name: Setup Python, Poetry and cache dependencies
description: Setup Python and installs Poetry, also cache installed dependencies
runs:
  using: composite
  steps:
    - name: Setup Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
      shell: bash
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'
