name: Create Pull Request
description: Commit changes to a new branch and creates a new Pull Request
inputs:
  files-to-commit:
    description: Files to be committed, all if not specified
    required: false
    default: '.'
    type: string
  commit-message:
    description: Commit message to be used in the workflow run
    required: false
    default: 'ci[ACTION]: create-pull-request'
    type: string
  branch-prefix:
    description: Prefix to be used while creating a new branch
    required: true
    type: string
  pr-title:
    description: Title of the new Pull Request
    required: true
    type: string
  pr-template:
    description: Template to be used as body of the Pull Request
    required: true
    type: string
  pr-reviewer:
    description: Reviewer(s) of the Pull Request
    required: true
    type: string
  pr-assignee:
    description: Assignee(s) of the Pull Request
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Configure commit author
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
      shell: bash
    - name: Commit changes
      run: |
        git add ${{ inputs.files-to-commit }}
        git commit --no-verify -m "${{ inputs.commit-message }}"
      shell: bash
    - name: Get short commit hash
      id: short-hash
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Set branch name
      id: branch-name
      run: |
        branch_prefix=${{ inputs.branch-prefix }}
        branch_sufix=${{ steps.short-hash.outputs.hash }}
        branch_name="${branch_prefix}-${branch_sufix}"
        echo "branch=${branch_name}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Create a new branch and push to origin
      env:
        NEW_BRANCH_NAME: ${{ steps.branch-name.outputs.branch }}
      run: |
        git checkout -b ${{ env.NEW_BRANCH_NAME }}
        git push -u origin ${{ env.NEW_BRANCH_NAME }}
      shell: bash
    - name: Create a new Pull Request
      run: |
        gh pr create \
          --title "${{ inputs.pr-title }}" \
          --body-file ${{ inputs.pr-template }} \
          --reviewer ${{ inputs.pr-reviewer }} \
          --assignee ${{ inputs.pr-assignee }} \
          --fill
      shell: bash
