name: Create Pull Request
description: Commit changes to a new branch and creates a new Pull Request, bot account (GPG key) is required to sign commits
inputs:
  files-to-commit:
    description: Files to be committed, all if not specified
    required: false
    default: '.'
    type: string
  commit-message:
    description: Commit message to be used in the workflow run
    required: false
    default: 'ci[ACTION]: create-pull-request'
    type: string
  branch-prefix:
    description: Prefix to be used while creating a new branch
    required: true
    type: string
  pr-title:
    description: Title of the new Pull Request
    required: true
    type: string
  pr-template:
    description: Template to be used as body of the Pull Request
    required: true
    type: string
  pr-reviewer:
    description: Reviewer(s) of the Pull Request
    required: true
    type: string
  pr-assignee:
    description: Assignee(s) of the Pull Request
    required: true
    type: string
  BOT_GPG_PRIVATE_KEY:
    description: Bot account's GPG private key
    required: true
    type: string
  BOT_GPG_PASSPHRASE:
    description: Bot's GPG passphrase, required to access the private key
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Import bot's GPG key for signing commits
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ inputs.BOT_GPG_PRIVATE_KEY }}
        passphrase: ${{ inputs.BOT_GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Commit changes
      run: |
        git add ${{ inputs.files-to-commit }}
        git commit --no-verify -m "${{ inputs.commit-message }}"
      env:
        GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
        GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
      shell: bash
    - name: Get short commit hash
      id: short-hash
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Set branch name
      id: branch-name
      run: |
        branch_prefix=${{ inputs.branch-prefix }}
        branch_sufix=${{ steps.short-hash.outputs.hash }}
        branch_name="${branch_prefix}-${branch_sufix}"
        echo "branch=${branch_name}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Create a new branch and push to origin
      env:
        NEW_BRANCH_NAME: ${{ steps.branch-name.outputs.branch }}
      run: |
        git checkout -b ${{ env.NEW_BRANCH_NAME }}
        git push -u origin ${{ env.NEW_BRANCH_NAME }}
      shell: bash
    - name: Create a new Pull Request
      run: |
        gh pr create \
          --title "${{ inputs.pr-title }}" \
          --body-file ${{ inputs.pr-template }} \
          --reviewer ${{ inputs.pr-reviewer }} \
          --assignee ${{ inputs.pr-assignee }} \
          --fill
      shell: bash
